[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# Floats defaulting to mediump causes a bunch of visual issues. we can't have that

# leaving this here because it prevents a compile error in some shaders
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''(extern|uniform)\s+(number|float|vec2|vec3|vec4|mat2|mat3|mat4)'''
payload = '''$1 highp $2'''
position = 'at'

### let's put this on the wall of jank
# [[patches]]
# [patches.regex]
# target = "GLSL_ES_PATCHES.fs"
# pattern = '''([\n(]\s*)(number|float|vec2|vec3|vec4|mat2|mat3|mat4)([^=\n]*=)'''
# payload = '''$1 highp $2$3'''
# position = 'at'

# # uninitialized variables but NOT function heads
# [[patches]]
# [patches.regex]
# target = "GLSL_ES_PATCHES.fs"
# pattern = '''(\n\s*)(number|float|vec2|vec3|vec4|mat2|mat3|mat4)([^=\n(]*;)'''
# payload = '''$1 highp $2$3'''
# position = 'at'

# what could go wrong
[[patches]]
[patches.pattern]
target = '=[love "wrap_GraphicsShader.lua"]'
pattern = 'precision mediump float;'
payload = 'precision highp float;'
position = 'at'
match_indent = true