[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

### CLEANUP: false positives

# comparisons in preprocessor directives
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''(__\w+__\s*[<>]\s*\d+)\.'''
payload = '$1'
position = 'at'

# scientific notation
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''([\d.]e\-?\d+)\.'''
payload = '$1'
position = 'at'

# array length/index
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''\[(\d+)\.\]'''
payload = '[$1]'
position = 'at'

# fall back to explicit int conversion when the above patch doesn't work
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''\[([^\[\]]*[^\d.][^\[\]]*)\]'''
payload = '[int($1)]'
position = 'at'

# remove unsupported float suffixes
# matching the full decimals because of an inexplicable space it adds before what's matched
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''(?<n>(\d+\.)?\d+)f'''
payload = '$n'
position = 'at'

# remove uniform from named globals (we're hoping they're constant, otherwise shit breaks)
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''(extern|uniform)([^=\n]*=.*)'''
payload = '$2'
position = 'at'