[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

### Sprite API

# Card:set_sprites()
[[patches]]
[patches.regex]
target = 'card.lua'
pattern = 'G.ASSET_ATLAS\["centers"\]'
position = 'at'
payload = "G.ASSET_ATLAS[(G.GAME.viewed_back or G.GAME.selected_back) and ((G.GAME.viewed_back or G.GAME.selected_back)[G.SETTINGS.colourblind_option and 'hc_atlas' or 'lc_atlas'] or (G.GAME.viewed_back or G.GAME.selected_back).atlas) or 'centers']"

[[patches]]
[patches.regex]
target = 'card.lua'
pattern = 'G.ASSET_ATLAS\[_center.atlas or _center.set\]'
position = 'at'
payload = "G.ASSET_ATLAS[SMODS.UndiscoveredSprites[_center.set] and (SMODS.UndiscoveredSprites[_center.set][G.SETTINGS.colourblind_option and 'hc_atlas' or 'lc_atlas'] or SMODS.UndiscoveredSprites[_center.set].atlas) or _center.set]"

[[patches]]
[patches.regex]
target = 'card.lua'
pattern = "G.ASSET_ATLAS\\['Joker'\\]"
position = 'at'
payload = "G.ASSET_ATLAS[_center[G.SETTINGS.colourblind_option and 'hc_atlas' or 'lc_atlas'] or _center.atlas or _center.set]"

[[patches]]
[patches.regex]
target = 'card.lua' 
pattern = 'G.ASSET_ATLAS\[_center.set\]'
position = 'at'
payload = "G.ASSET_ATLAS[_center[G.SETTINGS.colourblind_option and 'hc_atlas' or 'lc_atlas'] or _center.atlas or _center.set]"

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "(_center.set == 'Joker' and G.j_undiscovered.pos) or"
position = 'before'
payload = 'SMODS.UndiscoveredSprites[_center.set] and SMODS.UndiscoveredSprites[_center.set].pos or'
match_indent = true

[[patches]]
[patches.regex]
target = 'card.lua' 
pattern = '(_front\.atlas and )?G.ASSET_ATLAS\[_front\.atlas\]'
position = 'at'
payload = 'G.ASSET_ATLAS[G.SETTINGS.colourblind_option and _front.hc_atlas or _front.lc_atlas] or G.ASSET_ATLAS[_front.atlas]'


# Game:set_render_settings()
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "G:set_render_settings()"
position = 'at'
match_indent = true
payload = "SMODS.injectObjects(SMODS.Atlas)"
