[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

## Fixes for Wee Joker, Lucky Cat and 8-Ball juicing wrong cards
## all issues were caused by missing scored_card values
# Also Card:calculate_joker(context)
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'before'
pattern = '''extra = {focus = self, message = localize('k_upgrade_ex')},'''
payload = 'scored_card = self,'
match_indent = true
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'before'
pattern = '''extra = {focus = self, message = localize('k_upgrade_ex'), colour = G.C.MULT},'''
payload = 'scored_card = self,'
match_indent = true
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'before'
pattern = '''extra = {focus = self, message = localize('k_plus_tarot'), func = function()'''
payload = 'scored_card = self,'
match_indent = true