[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

## Blind API elseif chain reverts
# revert the change for The Pillar
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = "elseif self.name == 'The Pillar' and card.ability.played_this_ante then"
position = 'at'
payload = '''end
if self.name == 'The Pillar' and card.ability.played_this_ante then'''
match_indent = true

# revert the change for The Eye in debuff_hand
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = "elseif self.name == 'The Eye' then"
position = 'at'
payload = '''end
if self.name == 'The Eye' then'''
match_indent = true