[manifest]
version = "1.0.0"
dump_lua = true
priority = -5

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if true then
            if from_debuff then
                self.ability.joker_added_to_deck_but_debuffed = nil
            else
                if self.edition and self.edition.card_limit then
                    if self.ability.consumeable then
                        G.consumeables.config.card_limit = G.consumeables.config.card_limit + self.edition.card_limit
                    else
                        G.jokers.config.card_limit = G.jokers.config.card_limit + self.edition.card_limit
                    end
                end
            end
        end
        if G.GAME.blind and G.GAME.blind.in_blind then G.E_MANAGER:add_event(Event({ func = function() G.GAME.blind:set_blind(nil, true, nil); return true end })) end'''
position = "after"
match_indent = true
payload = '''
if not from_debuff and G.hand then
    local is_playing_card = self.ability.set == 'Default' or self.ability.set == 'Enhanced'
    
    -- TARGET: calculate card_added

    if not is_playing_card then
        SMODS.calculate_context({card_added = true, card = self})
    end
end
'''
