[manifest]
version = "1.0.0"
dump_lua = true
priority = -5


#
# End of round money
#

# Hide off screen rows

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if config.name ~= 'bottom' then"
position = "after"
payload = '''
    total_cashout_rows = (total_cashout_rows or 0) + 1
    if total_cashout_rows > 7 then
        return
    end'''
match_indent = true