[manifest]
version = "1.0.0"
dump_lua = true
priority = -11

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "function love.errhand(msg)"
position = "at"
payload = "if false then"
match_indent = true

[[patches]]
[patches.module]
source = "src/crash_handler/additional_context.lua"
name = "SMODS.crash_handler.additional_context"

[[patches]]
[patches.module]
source = "src/crash_handler/errorgen.lua"
name = "SMODS.crash_handler.errorgen"

[[patches]]
[patches.module]
source = "src/crash_handler/stack_format.lua"
name = "SMODS.crash_handler.stack_format"

[[patches]]
[patches.module]
source = "src/crash_handler/handler.lua"
name = "SMODS.crash_handler.handler"
before = "main.lua"
load_now = true

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
position = 'after'
pattern = '''
local saveTable = args.savetext or nil
'''
payload = '''
if G.SAVED_GAME then SMODS.save_game = G.SAVED_GAME.GAME.smods_version else SMODS.save_game = nil end
'''
