[manifest]
version = "1.0.0"
dump_lua = true
priority = -10


# game:update() inject SMODS.GameStates
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
        if self.STATE == self.STATES.MENU then
            self:update_menu(dt)
        end
'''
position = 'after'
match_indent = true
payload = '''
if SMODS.GameStates[self.STATE] then
    SMODS.GameStates[self.STATE]:update(dt)
end
'''
