[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
pattern = 'G\.GAME\.interest_cap/5'
position = 'at'
payload = '(G.GAME.interest_cap/(5 + (G.GAME.add_per_interest or 0)) + (G.GAME.add_interest_cap or 0))'

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
pattern = 'vars = \{G\.GAME\.interest_amount, 5'
position = 'at'
payload = 'vars = {G.GAME.interest_amount, (5 + (G.GAME.add_per_interest or 0))'

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = 'G\.GAME\.interest_cap/5'
position = 'at'
payload = '(G.GAME.interest_cap/(5 + (G.GAME.add_per_interest or 0)) + (G.GAME.add_interest_cap or 0))'

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = 'G\.GAME\.dollars/5'
position = 'at'
payload = 'G.GAME.dollars/(5 + (G.GAME.add_per_interest or 0))'
