[manifest]
version = "1.0.0"
priority = 0

# Game.set_language
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''v.FONT = love.graphics.newFont( v.file, v.render_scale)'''
payload = 'v.FONT = nil; SMODS.defer_font(v)'
position = 'at'
match_indent = true


# Game.set_render_settings
[[patches]]
[patches.regex]
target = 'game.lua'
pattern = '''image = love\.graphics\.newImage\([^\)]+\)'''
payload = 'image = nil'
position = 'at'

# Game.set_render_settings
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = 'v:reset()'
payload = ''
position = 'at'
match_indent = true
