[manifest]
version = "1.0.0"
dump_lua = true
priority = 100

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''          G.SHADERS['CRT']:send('hovering', 1)
          love.graphics.setShader( G.SHADERS['CRT'])
          G.SETTINGS.GRAPHICS.crt = G.SETTINGS.GRAPHICS.crt/0.3'''
position = 'at'
match_indent = true
payload = '''          G.SHADERS['CRT']:send('hovering', 1)
          if G.SETTINGS.GRAPHICS.crt > 0 or G.SETTINGS.GRAPHICS.bloom > 1 then
              love.graphics.setShader(G.SHADERS['CRT'])
          else
              love.graphics.setShader()
          end
          G.SETTINGS.GRAPHICS.crt = G.SETTINGS.GRAPHICS.crt/0.3'''
