[manifest]
version = "1.0.0"
dump_lua = true
priority = 100

[[patches]]
[patches.pattern]
target = 'engine/sprite.lua'
pattern = '''        G.SHADERS[_shader or 'dissolve']:send('mouse_screen_pos', self.ARGS.prep_shader.cursor_pos)
        G.SHADERS[_shader or 'dissolve']:send('screen_scale', G.TILESCALE*G.TILESIZE*(_draw_major.mouse_damping or 1)*G.CANV_SCALE)
        G.SHADERS[_shader or 'dissolve']:send('hovering',((_shadow_height  and not tilt_shadow) or _no_tilt) and 0 or (_draw_major.hover_tilt or 0)*(tilt_shadow or 1))
        G.SHADERS[_shader or 'dissolve']:send("dissolve",math.abs(_draw_major.dissolve or 0))
        G.SHADERS[_shader or 'dissolve']:send("time",123.33412*(_draw_major.ID/1.14212 or 12.5123152)%3000)
        G.SHADERS[_shader or 'dissolve']:send("texture_details",self:get_pos_pixel())
        G.SHADERS[_shader or 'dissolve']:send("image_details",self:get_image_dims())
        G.SHADERS[_shader or 'dissolve']:send("burn_colour_1",_draw_major.dissolve_colours and _draw_major.dissolve_colours[1] or G.C.CLEAR)
        G.SHADERS[_shader or 'dissolve']:send("burn_colour_2",_draw_major.dissolve_colours and _draw_major.dissolve_colours[2] or G.C.CLEAR)
        G.SHADERS[_shader or 'dissolve']:send("shadow",(not not _shadow_height))
        if _send then
            G.SHADERS[_shader or 'dissolve']:send((SMODS.Shaders[_shader or 'dissolve'] and SMODS.Shaders[_shader or 'dissolve'].original_key) or _shader,_send)
        end'''
position = 'at'
match_indent = true
payload = '''        local shader_obj = G.SHADERS[_shader or 'dissolve']
        shader_obj:send('mouse_screen_pos', self.ARGS.prep_shader.cursor_pos)
        shader_obj:send('screen_scale', G.TILESCALE*G.TILESIZE*(_draw_major.mouse_damping or 1)*G.CANV_SCALE)
        shader_obj:send('hovering',((_shadow_height  and not tilt_shadow) or _no_tilt) and 0 or (_draw_major.hover_tilt or 0)*(tilt_shadow or 1))
        shader_obj:send("dissolve",math.abs(_draw_major.dissolve or 0))
        shader_obj:send("time",123.33412*(_draw_major.ID/1.14212 or 12.5123152)%3000)
        shader_obj:send("texture_details",self:get_pos_pixel())
        shader_obj:send("image_details",self:get_image_dims())
        shader_obj:send("burn_colour_1",_draw_major.dissolve_colours and _draw_major.dissolve_colours[1] or G.C.CLEAR)
        shader_obj:send("burn_colour_2",_draw_major.dissolve_colours and _draw_major.dissolve_colours[2] or G.C.CLEAR)
        shader_obj:send("shadow",(not not _shadow_height))
        if _send then
            shader_obj:send((SMODS.Shaders[_shader or 'dissolve'] and SMODS.Shaders[_shader or 'dissolve'].original_key) or _shader,_send)
        end'''

[[patches]]
[patches.pattern]
target = 'engine/sprite.lua'
pattern = '''    love.graphics.setShader( G.SHADERS[_shader or 'dissolve'],  G.SHADERS[_shader or 'dissolve'])'''
position = 'at'
match_indent = true
payload = '''    local shader_obj = G.SHADERS[_shader or 'dissolve']
    love.graphics.setShader( shader_obj,  shader_obj)'''
