[manifest]
version = "1.0.0"
dump_lua = true
priority = 100

[[patches]]
[patches.pattern]
target = 'engine/moveable.lua'
pattern = '''
function Moveable:calculate_parrallax()
    if not G.ROOM then return end
    self.shadow_parrallax.x = (self.T.x + self.T.w/2 - G.ROOM.T.w/2)/(G.ROOM.T.w/2)*1.5
end
'''
position = 'at'
match_indent = true
payload = '''
function Moveable:calculate_parrallax()
    if self.STATIONARY then return end
    if not G.ROOM then return end
    self.shadow_parrallax.x = (self.T.x + self.T.w/2 - G.ROOM.T.w/2)/(G.ROOM.T.w/2)*1.5
end
'''

[[patches]]
[patches.pattern]
target = 'engine/moveable.lua'
pattern = '''
function Moveable:move_xy(dt)
    if  (self.T.x ~= self.VT.x or math.abs(self.velocity.x) > 0.01) or 
        (self.T.y ~= self.VT.y or math.abs(self.velocity.y) > 0.01) then
        self.velocity.x = G.exp_times.xy*self.velocity.x + (1-G.exp_times.xy)*(self.T.x - self.VT.x)*35*dt
        self.velocity.y = G.exp_times.xy*self.velocity.y + (1-G.exp_times.xy)*(self.T.y - self.VT.y)*35*dt
        if self.velocity.x*self.velocity.x + self.velocity.y*self.velocity.y > G.exp_times.max_vel*G.exp_times.max_vel then 
            local actual_vel = math.sqrt(self.velocity.x*self.velocity.x + self.velocity.y*self.velocity.y)
            self.velocity.x = G.exp_times.max_vel*self.velocity.x/actual_vel
            self.velocity.y = G.exp_times.max_vel*self.velocity.y/actual_vel
        end
'''
position = 'at'
match_indent = true
payload = '''
function Moveable:move_xy(dt)
    if  (self.T.x ~= self.VT.x or math.abs(self.velocity.x) > 0.01) or 
        (self.T.y ~= self.VT.y or math.abs(self.velocity.y) > 0.01) then
        self.velocity.x = G.exp_times.xy*self.velocity.x + (1-G.exp_times.xy)*(self.T.x - self.VT.x)*35*dt
        self.velocity.y = G.exp_times.xy*self.velocity.y + (1-G.exp_times.xy)*(self.T.y - self.VT.y)*35*dt
        local vel_sq = self.velocity.x*self.velocity.x + self.velocity.y*self.velocity.y
        if vel_sq > G.exp_times.max_vel*G.exp_times.max_vel then 
            local actual_vel = math.sqrt(vel_sq)
            self.velocity.x = G.exp_times.max_vel*self.velocity.x/actual_vel
            self.velocity.y = G.exp_times.max_vel*self.velocity.y/actual_vel
        end
'''
