[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# Shader patching
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''            self.SHADERS[shader_name] = love.graphics.newShader("resources/shaders/"..filename)'''
position = "before"
payload = '''
local shader = "resources/shaders/"..filename
local lovely = require"lovely"
if lovely.apply_patches then
    shader = lovely.apply_patches(filename, love.filesystem.read("resources/shaders/"..filename))
end
'''
match_indent = true