[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# Allow use stencil in global canvas
# Game:draw()
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''love.graphics.setCanvas{self.CANVAS}'''
position = "at"
payload = '''
love.graphics.setCanvas{self.CANVAS, depthstencil = SMODS.stencil_canvas}
'''
match_indent = true

# Limit overflow container size
# UIBox:calculate_xywh()
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''_nt.h = math.max(_ct.h + padding, _nt.h)-- '''
position = "after"
payload = '''
if node.config and node.config.no_overflow then
    if string.find(node.config.no_overflow, "h") then
        if node.config.w then
            _nt.w = node.config.w
        elseif node.config.maxw then
            _nt.w = math.min(_nt.w, node.config.maxw)
        end
    end
    if string.find(node.config.no_overflow, "v") then
        if node.config.h then
            _nt.h = node.config.h
        elseif node.config.maxh then
            _nt.h = math.min(_nt.h, node.config.maxh)
        end
    end
end
'''
match_indent = true

# Prevent text be rescaled by overflow container
# UIBox:calculate_xywh()
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''fac = fac*restriction/(node.config.maxw and _ct.w or _ct.h)'''
position = "after"
payload = '''
if node.config.no_overflow and string.find(node.config.no_overflow, node.config.maxw and "h" or "v") then fac = _scale or 1 end
'''
match_indent = true

# Limit overflow container size during filling
# UIElement:set_wh()
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''if w.UIT == G.UIT.C then w.T.h = _max_h end'''
position = "after"
payload = '''
if w.config and w.config.no_overflow then
    if string.find(w.config.no_overflow, "h") then
        if w.config.w then
            w.T.w = w.config.w
        elseif w.config.maxw then
            w.T.w = math.min(w.T.w, w.config.maxw)
        end
    end
    if string.find(w.config.no_overflow, "v") then
        if w.config.h then
            w.T.h = w.config.h
        elseif w.config.maxh then
            w.T.h = math.min(w.T.h, w.config.maxh)
        end
    end
end
'''
match_indent = true

# Exclude overflowed elements from colliding
# Controller:get_cursor_collision()
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''if v:collides_with_point(cursor_trans) and not v.REMOVED then'''
position = "at"
payload = '''
local point = v.container == G.ROOM and _p or cursor_trans
if v:collides_with_point(point) and not v.REMOVED and v:inside_overflow_boundaries(point) then
'''
match_indent = true

# Calculate G.ROOM point beforehand
# Controller:get_cursor_collision()
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''local DRAW_HASH_SQUARE = G.DRAW_HASH'''
position = "before"
payload = '''
self.ARGS = self.ARGS or {}
self.ARGS.room_collides_with_point_point = self.ARGS.room_collides_with_point_point or { smods_is_room_point = true }
self.ARGS.room_collides_with_point_translation = self.ARGS.room_collides_with_point_translation or {}
self.ARGS.room_collides_with_point_rotation = self.ARGS.room_collides_with_point_rotation or {}
local _p = self.ARGS.room_collides_with_point_point
local _t = self.ARGS.room_collides_with_point_translation
local _r = self.ARGS.room_collides_with_point_rotation
_p.x, _p.y = cursor_trans.x, cursor_trans.y

if math.abs(G.ROOM.T.r) < 0.1 then
    --Translate to normalize this Node to the center of the container
    _t.x, _t.y = -G.ROOM.T.w/2, -G.ROOM.T.h/2
    point_translate(_p, _t)

    --Rotate node about the center of the container
    point_rotate(_p, G.ROOM.T.r)
    
    --Translate node to undo the container translation, essentially reframing it in 'container' space
    _t.x, _t.y = G.ROOM.T.w/2-G.ROOM.T.x, G.ROOM.T.h/2-G.ROOM.T.y
    point_translate(_p, _t)
else
    --Translate node to undo the container translation, essentially reframing it in 'container' space
    _t.x, _t.y = -G.ROOM.T.x, -G.ROOM.T.y
    point_translate(_p, _t)
end
'''
match_indent = true

# Use room point to speedup collision calculations
# Node:collides_with_point()
[[patches]]
[patches.pattern]
target = "engine/node.lua"
pattern = '''if self.container ~= self then --if there is some valid container, we need to apply all translations and rotations for the container first'''
position = "at"
payload = '''
if self.container ~= self and not point.smods_is_room_point then --if there is some valid container, we need to apply all translations and rotations for the container first
'''
match_indent = true